# Generated by Django 5.2 on 2025-06-25 07:08

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_scrap_post_scrap"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to=posts.models.upload_filepath),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, upload_to=posts.models.upload_filepath),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories_postcategory",
                to="posts.category",
            ),
        ),
        migrations.AlterField(
            model_name="postcategory",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_postcategory",
                to="posts.post",
            ),
        ),
    ]
