# Generated by Django 5.1.7 on 2025-06-23 09:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_like_post_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="posts", through="blog.PostCategory", to="blog.category"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to=blog.models.upload_filepath),
        ),
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, upload_to=blog.models.upload_filepath),
        ),
    ]
