# Generated by Django 5.1.7 on 2025-06-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_category_post_categories_post_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="categories",
            new_name="category",
        ),
    ]
