# Generated by Django 5.1.7 on 2025-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("phone_num", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("create_at", models.DateField()),
            ],
        ),
    ]
